### ISSUE TITLE
Question: Any reason this couldn't work in a PortableClass Library

### ISSUE THREAD

**Issue by paul1956** [SLaks/ConfOxide#3]
I am trying to use it in a CodeAnalyzer in VS2015 REL.

**Comment by SLaks** [comment]
Hmm...

I'd have to figure out what to do with https://github.com/SLaks/ConfOxide/blob/master/ConfOxide/SettingsFileExtensions.cs, which won't work in a PCL.

**Comment by paul1956** [comment]
What specifically won't work?

**Comment by SLaks** [comment]
The `File` class (`Open()` and `Exists()`)

**Comment by paul1956** [comment]
If I implement this would it be sufficient?
```
namespace ConfOxide
{
	internal class File
	{
		static internal bool Exists(string jsonPath)
		{
			throw new NotImplementedException();
		}

		static internal TextReader OpenText(string jsonPath)
		{
			throw new NotImplementedException();
		}

		static internal IDisposable Open(string jsonPath, FileMode openOrCreate)
		{
			throw new NotImplementedException();
		}
	}
}
```

**Comment by paul1956** [comment]
I am having more issues with all the Type.is??? those does seem to exist in PCL.

**Comment by SLaks** [comment]
No, because those APIs need to actually work (in particular, Web Essentials calls them).
This cannot work in PCL.

I think I'd need separate builds & projects for PCL and non-PCL, which would be annoying.

And, you'd need to port the `TypeExtensions` to the PCL reflection APIs, which is mostly simple (except for `GetListElementType`).

I started working on that, and got 

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;

namespace ConfOxide.MemberAccess {
	///<summary>Contains extension methods for Type instances.</summary>
	public static class TypeExtensions {

		static readonly HashSet<Type> scalarTypes = new HashSet<Type> { typeof(decimal), typeof(string), typeof(DateTime), typeof(DateTimeOffset), typeof(TimeSpan), typeof(Uri) };
		///<summary>Checks whether a type is valid as a single settings value.</summary>
		public static bool IsScalarType(this Type type) {
			type = Nullable.GetUnderlyingType(type) ?? type;
			if (type.IsPrimitive || type.IsEnum)
				return true;
			if (scalarTypes.Contains(type))
				return true;
			return false;
		}

		///<summary>Checks whether a type inherits <see cref="SettingsBase{T}"/>.</summary>
		public static bool IsSettingsType(this Type type) {
			var baseType = type.GetTypeInfo().BaseType.GetTypeInfo();
            if (!baseType.IsGenericType)
				return false;
			if (baseType.GetGenericTypeDefinition() == typeof(SettingsBase<>)
			 && baseType.GenericTypeArguments[0] == (type.GetTypeInfo().IsGenericTypeDefinition ? type.GetTypeInfo().GetGenericArguments()[0] : type))
				return true;
			if (baseType.GetGenericTypeDefinition().IsSettingsType())
				return true;
			return false;
		}

		///<summary>Gets the element type of a type inheriting <see cref="IList{T}"/>, or null for non-List types.</summary>
		public static Type GetListElementType(this Type type) {
			if (type.GetTypeInfo().IsGenericType && type.GetGenericTypeDefinition() == typeof(IList<>))
				return type.GenericTypeArguments[0];
			var superInterface = type.GetTypeInfo().GetRuntimeInterfaceMap("System.Collections.Generic.IList`1");
			if (superInterface == null)
				return null;
			return superInterface.GetGenericArguments()[0];
		}
	}
}
```

**Comment by paul1956** [comment]
Sorry for being unclear, what I intended to do was implement the stubs that Visual Studio gave me above,and remove the notimplemented exceptions. Then I realized that the TypeExtensions were also a problem.

**Comment by paul1956** [comment]
Isn't the non-PCL a superset of PCL so you only need that one?

**Comment by SLaks** [comment]
No; if you make those stubs, it will always bind to them, and never actually work.
There is no way to conditionally bind to different methods in the same compilation.

**Comment by paul1956** [comment]
I don't want to make the stubs, Visual Studio did that, I want to implement the three functions just like you are implementing the missing TypeExtensions.

**Comment by paul1956** [comment]
Please ignore  last message I will delete when I get to a computer.

**Comment by paul1956** [comment]
How do Roslyn APIs work if they can't write to disk? Is this why a lot Visual Studio Ectensions are implemented as a single VSIX with all the code instead of a thin VSIX project with a separate PCL like the templates?

**Comment by SLaks** [comment]
Only the innermost layers of Roslyn (the core compiler) are PCLs.  See [my blog](http://blog.slaks.net/2014-04-07/exploring-roslyn-part-1-introduction/) for more details.
The rest of Roslyn, and Visual Studio and almost all VS extensions, are normal desktop projects.

**Comment by paul1956** [comment]
The default projects for analyzes, diagnostics and refactoring are all PCL, how am I supposed to know I shouldn't be using that and how do I change projects to stop using PCL.

**Comment by SLaks** [comment]
These projects are supposed to be self-contained (not reading disk), so PCL is fine.

To switch, just create a new desktop Class Library project and add the same Roslyn NuGet packages.

**Comment by paul1956** [comment]
So we get back to my original issue, I need options for one of them.

**Comment by SLaks** [comment]
Just move your code to a normal desktop library project (with the same references from NuGet) and use that.

**Comment by paul1956** [comment]
I think it is more complicated that that. Only the VSIX project seems to have a usable reference to the solution/project files. It seems that everything really needs to go in that project as I have seen in other open source Visual Studio extension projects or I am missing how analyzes are supposed to implement user options.

Sent from my iPhone
I apologize for any typos Siri might have made.
(503) 803-6077

**Comment by SLaks** [comment]
Correct; the analyzer project cannot talk directly to VS.
If your analyzer itself needs to talk to VS, there is no point in having two projects.

I think the canonical way to make a configurable analyzer is to use Roslyn's `Option<T>` class, and look up the options from the workspace.  You would then write code in the VSIX to populate the options in the Roslyn workspace from some kind of configuration, while other non-VS hosts could configure your analyzer through other means.

**Comment by paul1956** [comment]
I wish someone had told me that a month ago and the built in templates offered that option or made it clear before I wasted so much time.  I will post something under the Roslyn issues.
